name: ci
on:
  push:
  pull_request:

jobs:
  pylama:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: pip install pylama
      - run: pylama packethardware setup.py
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: pip install black
      - run: black --check --diff .
  publish-docker-image:
    name: build image and possibly push image to quay.io
    runs-on: ubuntu-latest
    needs: [pylama, black]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: 'true'
      - uses: docker/setup-buildx-action@v1
        id: buildx
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: quay.io/packet/packet-hardware
          tags: |
            type=sha
            type=ref,event=branch
      - uses: docker/login-action@v1
        if: github.event_name == 'create' && github.event.ref_type == 'tag'
        with:
          registry: quay.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-cache
          restore-keys: |
            ${{ runner.os }}-cache
      - uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          push: ${{ github.event_name == 'create' && github.event.ref_type == 'tag' }}
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          builder: ${{ steps.buildx.outputs.name }}
